import express from "express";
import { loginUser } from "../user/user.controller";
import {postService, getAllServiceController, getServiceByCategoryIdController, updateServiceController, deleteServiceController} from './services.controller';
const router = express.Router();
router.post("/create-service", postService);
router.get("/services", getAllServiceController);
router.patch("/services", updateServiceController);
router.delete("/services/:id", deleteServiceController);
router.get("/services/:categoryId", getServiceByCategoryIdController);
export const shebaServices = router;
