apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sheba-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "sheba-backend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sheba-backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sheba-backend.name" . }}
    spec:
      containers:
        - name: sheba-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3333
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
