---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "sheba-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway # Use the default Istio ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"  # Replace with your domain in production
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "sheba-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "*"  # Replace with your domain in production
  gateways:
    - {{ include "sheba-backend.fullname" . }}
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: {{ include "sheba-backend.fullname" . }}
            port:
              number: 4000
    - route:
        - destination:
            host: {{ include "sheba-backend.fullname" . }}
            port:
              number: 3333
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "sheba-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "sheba-backend.fullname" . }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL  # Enable mTLS between services
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: v1
      labels:
        version: v1
