apiVersion: v1
kind: Service
metadata:
  name: {{ include "sheba-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "sheba-backend.name" . }}
  type: ClusterIP
  ports:
    - name: http
      port: 3333
      targetPort: 3333
    - name: api
      port: 4000
      targetPort: 4000
