apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sheba-application
  namespace: sheba
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nayem9b/Sheba.xyz-backend.git  # Your chart repo
    targetRevision: HEAD
    path: charts/sheba-backend  # Path to your Helm chart
    helm:
      releaseName: sheba-backend
      values: |
        image:
          repository: nayem9b/sheba-backend-github-build  # Your Docker Hub image
          tag: latest  # Or use a specific tag
  destination:
    server: https://kubernetes.default.svc
    namespace: sheba
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
# tiVEwcWX1xn1bvdZ