name: Docker Image CI

on:
  pull_request:
    types: [closed]
    branches: [ "prod" ]
    # Only run when PR is merged to prod
    # paths-ignore:
    #   - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: nayem9b/sheba-backend-github-build:latest
